### PR TITLE
🛠️ Fix ➾ Closes #1824, transfer task not finding aliases

### LINKED ISSUE #1824: 🐛 Bug ➾ `taq transfer` not finding contract aliases in local environment config file
### 🚥 Status (Internal Taqueria Team Use Only)

- [x] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

Here's my config.local.testing.json file:
```
{
    "contracts": {
        "example": {
            "address": "KT1Ldk5KioyThwp5SYB3gDqSWYU2CPbC9XGM"
        }
    },
    "networkName": "ghostnet",
    "accounts": {
        "bob": {
            "publicKey": "edpkvDTiZvYregVTMNifvz2H2J7njQApP7nhc5XHWZZnGkJzCPwsKP",
            "publicKeyHash": "tz1MVQAjKr2Y9SDCTJkoZwiWGfXjSmsCz6h2",
            "privateKey": "edskRkWhbUr1wmEbRNbWXEHwTjRmFihfqe1ahnoX1UTGw2fNKh5yybYhZ9uL3w83wm1TCWRpEByB3vSvnr55Wfi1AqfJZvV42P",
            "mnemonic": "ugly fold nasty dumb insect salon wear build grid tonight peace bottom"
        },
        "alice": {
            "publicKey": "edpktipPPomKV1JxQRap6LJzFmhiituDqJkYoWgHKqbj78kJm4nv5M",
            "publicKeyHash": "tz1QqQy27r58bFUcV9E6cGnM3jH9fKh82HP4",
            "privateKey": "edskSAc5Ye3uwNvcbknvHfkUkm9gTKheA5VDX2Gd99uTkbbMdV1ssSzqSxhDAGTo8SDiJg5mFoxNTNHpsm5MdDeg6hdETPTrv7",
            "mnemonic": "sphere cup feature rally flip dust fit tower type panda struggle universe"
        },
        "john": {
            "publicKey": "edpkutYUMurYaFXcuwi4ZLqsKhYYCHogc4ahTiHU1gyxbFtKiZFXTQ",
            "publicKeyHash": "tz1fJybRUg5mwWmH6rpTay1aD1Y5jMyHjcFH",
            "privateKey": "edskS3QYqYEWv9szqqL8hKWmG2eHXWgmuUuYitDNoHnG7F5U4uZqjeD3myxFh1bG8kWzQ71QrvtCF4cT1LUqb1NTCgvaB4MqSH",
            "mnemonic": "discover world seat buyer inform two climb hazard library noodle stereo decrease"
        },
        "jane": {
            "publicKey": "edpku3sKLs9hUjA7vqJxDVqYgfYrPpsvaCJ6npHA5uRiZJPCLez5AM",
            "publicKeyHash": "tz1P5STNMLjHPYHbitR3qNpJu11eUkANyT4y",
            "privateKey": "edskRkBqtdVBKddx2RJFaztYyiTtayu8Nc3fqcANa9KbBXaET4M8vaTXeje6ZZy3tFFHHv9Rb3bwRMDEHut52dmnngcALYCojH",
            "mnemonic": "join kite catalog regret deer anxiety equal cage ankle beach nut cream"
        },
        "joe": {
            "publicKey": "edpkuGchAPhuD3MjY66KREMEuBwKgoi4mWTGFCvJaUB4ChqTrAf6f5",
            "publicKeyHash": "tz1fNUMyV1B7uMGyine9Z2LTvNaNaXi2ibn4",
            "privateKey": "edskRuRBZBU6MyCrQaB5r6yfzDKispVwes4eqDC7xfh7pwnLMkzQWRtrPwdu2qWaGsC6SLQkM2hQUaZZ6ojn2yRtmX8KB16DEv",
            "mnemonic": "grace human valid slab main hurry satisfy ancient young horror bracket diamond"
        },
        "taqOperatorAccount": {
            "publicKey": "edpktwqjFAXUeziAAuMiCxWyuDcHjoJzvqFB3xepXQUChJyvcLrwSV",
            "publicKeyHash": "tz1YsNsD1zNkdTkmNb5UZW2QVwwabNW2GdDJ",
            "privateKey": "edskS3Pjs8KGcC7b1Bc1rr2U7fFPrcgwL1ZQhFupcHwXRB3jX8TVxC91Yi9ysfW2LNR3KNFxgnRCZSzX6sdPzUMxTMePQZK9Au",
            "mnemonic": "head jazz spirit metal barely box marble fury notable soul belt brain"
        }
    }
}
```

However, when I try to call the `increment` entrypoint using the `taq transfer` task I get:
```
Address for alias "eexample" is not present in the config.json. Make sure to deploy a contract with such alias.
No operations performed
```

### 🆘 Steps to Reproduce?

Using the `0.27.16-rc`.

1. Initialize a new project: `taq init test-project`
2. Navigate to the project: `cd test-project`
3. Install the ligo and taquito plugins: `taq install @taqueria/plugin-ligo@next && taq install @taqueria/plugin-taquito@next`
4. Create a new increment contract: `taq create contract example.jsligo`
5. Compile the contract: `taq compile example.jsligo`
6. Create the initial storage: `echo "1" > artifacts/example.default_storage.tz`
7. Switch environments: `taq set-environment testing`
8. Instantiate accounts: `taq instantiate-account`
9. Fund the accounts:  run `taq fund` and then follow the instructions to fund with 2001 tz via faucet. Then rerun `taq fund`.
10. Deploy the contract: `taq deploy example.tz`
11.  Create parameter file: `echo "1" > artifacts/example-increment-param.tz`
12. Call the increment entrypoint: `taq transfer --entrypoint increment example --param example-increment-param.tz`

Result: 
```
Address for alias "example." is not present in the config.json. Make sure to deploy a contract with such alias.
No operations performed
```

### 🪵 Relevant log output

_No response_

### 🐘 How impactful is this bug?

🤯 Major disruption

### ⏱️ Prevalance

daily

### 💻 Operating System

MacOS

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

v0.27.16-rc

### 🌿 Node.js Version

v16.16.0

### ☎️ Contact Details

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mweichert**
# 🌮 Taqueria PR

## 🪁 Description

The `taq transfer` task was not finding aliases in the Config runtime object due to a mis-transformation from V2 config.

## 🪂 Pre-Merge Checklist (Definition of Done)

🚦 Required to merge:

- [x] ⛱️ I have completed this PR template in full and updated the title appropriately
- [x] ⛵ My code builds cleanly, and I have manually tested the changes
- [ ] 🏄‍♂️ Another team member has built this branch and done manual testing on the change
- [x] 🏖️ New and existing unit tests pass locally and in CI
- [x] 🔱 The test plan has been implemented and verified by an SDET
- [x] 🦀 Automated tests have been written and added to this PR
- [x] 🐬 I have commented my code, particularly in hard-to-understand areas
- [x] 🤿 Corresponding changes have been made to all documentation
- [x] 🐚 Required changes to the VScE have been made
- [x] 🪸 Required updates to scaffolds have been made
- [ ] 🚢 The release checklist has been completed

## 🛩️ Summary of Changes

Added `aliases` to network config of the runtime Config object.

## 🎢 Test Plan

Re-run the steps in the issue.

### CODE REVIEW

File: taqueria-protocol/types-config-files.ts [hunk 1]
```diff
@@ -293,6 +293,7 @@ export const transformConfigToConfigFileV2 = (config: Config): ConfigFileSetV2 =
 
 // FileV2 to Object
 export const transformConfigFileV2ToConfig = (configFileSetV2: ConfigFileSetV2): Config => {
+	debugger;
```
Comment (jchenche) [inline taqueria-protocol/types-config-files.ts:296]: debugger

File: taqueria-vscode-extension/package.json [hunk 2]
```diff
@@ -53,24 +53,6 @@
 		"url": "https://github.com/ecadlabs/taqueria/issues"
 	},
 	"homepage": "https://github.com/ecadlabs/taqueria#readme",
-	"keywords": [
```
Comment (jchenche) [inline taqueria-vscode-extension/package.json:56]: why are they all removed?

File: taqueria-protocol/types-config-files.ts (hunk 1 above)
Comment (mweichert) [reply taqueria-protocol/types-config-files.ts]: Gesh, I could have sworn that I searched for these in my editor before committing. Thanks for catching Jimmy.

**Review by jchenche — APPROVED** [review]
