### PR TITLE
Unique port and name for sandboxes

### LINKED ISSUE #709: [Bug]: Cannot start more than one sandbox due to 19229 port on host machine always being used in the docker command
### What happened?

I went to go start two sandboxes with different protocols to check any differences but the docker command to start a sandbox is locked into using the host port 19229 like so: `sh -c "docker run --name test --rm --detach --platform linux/amd64 -p 20020:20000 -p 19229:9229 -v /home/alexander/taqueria/alex-1:/project -w /app ghcr.io/ecadlabs/taqueria-flextesa:dev-405-deploying-contracts-to-sandbox-f20ca3c node index.js --sandbox test"`

We can specify the port that will mainly be used but not being able to specify the other port stops us from being able to run multiple sandboxes at once

### What should have happened?

I should be able to run any number of sandboxes I want with any configuration of ports

### Steps to reproduce the bug

Steps to reproduce the error:

1. `taq init` a new project and run `npm init -y` inside of it
2. Download the flextesa plugin for taqueria
3. Copy the config.json file from the log output below into your projects .taq folder
4. Run the command `taq start sandbox local` and verify the sandbox starts with `docker ps -a`
5. Run the command `taq start sandbox test` and see it fail to start with the following message:
```
$ taq start sandbox test
Error: Command failed: sh -c "docker run --name test --rm --detach --platform linux/amd64 -p 20020:20000 -p 19229:9229 -v /home/alexander/taqueria/alex-1:/project -w /app ghcr.io/ecadlabs/taqueria-flextesa:dev-405-deploying-contracts-to-sandbox-f20ca3c node index.js --sandbox test"
docker: Error response from daemon: driver failed programming external connectivity on endpoint test (38f56d0732c8659788b8e494fd8e90301f2467eecce26faab278243266e33f69): Bind for 0.0.0.0:19229 failed: port is already allocated.

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  killed: false,
  code: 125,
  signal: null,
  cmd: 'sh -c "docker run --name test --rm --detach --platform linux/amd64 -p 20020:20000 -p 19229:9229 -v /home/alexander/taqueria/alex-1:/project -w /app ghcr.io/ecadlabs/taqueria-flextesa:dev-405-deploying-contracts-to-sandbox-f20ca3c node index.js --sandbox test"'
}
```

### Relevant log output

```shell
{
    "language": "en",
    "plugins": [
        {
            "name": "@taqueria/plugin-flextesa",
            "type": "npm"
        }
    ],
    "contractsDir": "contracts",
    "testsDir": "tests",
    "artifactsDir": "artifacts",
    "environment": {
        "default": "development",
        "development": {
            "networks": [],
            "sandboxes": [
                "local"
            ],
            "storage": {
                "hello-tacos.tz": "1",
                "increment.tz": "2"
            }
        }
    },
    "sandbox": {
        "local": {
            "accounts": {
                "default": "bob",
                "bob": {
                    "initialBalance": "3000000000"
                },
                "alice": {
                    "initialBalance": "2000000000"
                },
                "john": {
                    "initialBalance": "4000000000"
                },
                "jane": {
                    "initialBalance": "5000000000"
                },
                "joe": {
                    "initialBalance": "1000000000"
                }
            },
            "label": "Local Ithaca Tezos Sandbox",
            "protocol": "Psithaca2MLRFYargivpo7YvUr7wUDqyxrdhC5CQq78mRvimz6A",
            "rpcUrl": "http://localhost:20000"
        },
        "test": {
            "accounts": {
                "default": "ken",
                "ken": {
                    "initialBalance": "3000000000"
                },
                "tran": {
                    "initialBalance": "2000000000"
                },
                "mathew": {
                    "initialBalance": "4000000000"
                },
                "johnny": {
                    "initialBalance": "5000000000"
                },
                "maggie": {
                    "initialBalance": "1000000000"
                }
            },
            "label": "Test Jakarta Tezos Sandbox",
            "protocol": "PtJakart2xVj7pYXJBXrqHgd82rdkLey5ZeeGwDgPp9rhQUbSqY",
            "rpcUrl": "http://localhost:20020"
        }
    },
    "network": {}
}
```

### Screenshots and images

Screenshot and images

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #1014: [Feature]: unique sandbox name
### Describe the feature you would like

Suppose we have 2 different Taqueria projects and we want to start a sandbox named `"local"` in the first project, then we start another sandbox, also named `"local"`, in the second project. This won't work because running container names must be unique. To do this, we need to spin up docker containers with unique names derived from the project (hash of absolute path of the project maybe?). E.g. `"local-85f3d8e4bae5114a6eae12a7e46335f6073b2b1c"` and `"local-7056e17e9738b9e8843caadfeac3d7c3077fd327"`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jchenche**
Fixes #1014
Fixes #709

### CODE REVIEW

File: taqueria-plugin-flextesa/proxy.ts [hunk 1]
```diff
@@ -19,31 +31,66 @@ interface Opts extends RequestArgs.ProxyRequestArgs {
 
 const getDockerImage = (opts: Opts) => `ghcr.io/ecadlabs/taqueria-flextesa:${opts.setVersion}-${opts.setBuild}`;
 
-const getContainerName = (sandboxName: string, parsedArgs: Opts) => {
-	return `taqueria-${parsedArgs.env}-${sandboxName}`;
+const getUniqueSandboxname = async (sandboxName: string, projectDir: string) => {
+	const hash = await stringToSHA256(projectDir);
+	return `${sandboxName}-${hash}`;
+};
```
Comment (AlirezaHaghshenas) [inline taqueria-plugin-flextesa/proxy.ts:37]: I should update a related function in TVsCE. I'll do it in #1012

Comment (jchenche) [reply taqueria-plugin-flextesa/proxy.ts:37]: Ohhh didn't know it's in VSCode too. Btw `getContainerName()` uses this @AlirezaHaghshenas

Comment (jchenche) [reply taqueria-plugin-flextesa/proxy.ts:37]:
```typescript
const getUniqueSandboxname = async (sandboxName: string, projectDir: string) => {
	const hash = await stringToSHA256(projectDir);
	return `${sandboxName}-${hash}`;
};

const getContainerName = async (sandboxName: string, parsedArgs: Opts) => {
	const uniqueSandboxName = await getUniqueSandboxname(sandboxName, parsedArgs.projectDir);
	return `taqueria-${parsedArgs.env}-${uniqueSandboxName}`;
};
```

Comment (AlirezaHaghshenas) [reply taqueria-plugin-flextesa/proxy.ts:37]: Nice decision to include hash of project path in container name.

I don't see it being persisted anywhere in the config. If at a later stage a change causes this name to be persisted, we will have the problem that different people working on the same repository will constantly change each others' container names, because project path is different on their machines.

No such problem for now.

Comment (AlirezaHaghshenas) [reply taqueria-plugin-flextesa/proxy.ts:37]: Unfortunately, I cannot use these functions directly, as TVsCE code should not be dependent on a plugin's code.

For the moment, I duplicate this logic, and maintain it if changes are made to these functions.

@mweichert  might have a suggestion to stay DRY without adding dependency.

File: taqueria-plugin-flextesa/proxy.ts [hunk 2]
```diff
@@ -19,31 +31,66 @@ interface Opts extends RequestArgs.ProxyRequestArgs {
 
 const getDockerImage = (opts: Opts) => `ghcr.io/ecadlabs/taqueria-flextesa:${opts.setVersion}-${opts.setBuild}`;
 
-const getContainerName = (sandboxName: string, parsedArgs: Opts) => {
-	return `taqueria-${parsedArgs.env}-${sandboxName}`;
+const getUniqueSandboxname = async (sandboxName: string, projectDir: string) => {
```
Comment (AlirezaHaghshenas) [inline taqueria-plugin-flextesa/proxy.ts:34]:
```suggestion
const getUniqueSandboxName = async (sandboxName: string, projectDir: string) => {
```

**Review by alexzbusko — APPROVED** [review]
