### PR TITLE
Fix ➾ #1861, invalid TypeScript from `generate types` for contracts with entrypoints that have optional parameters

### LINKED ISSUE #1861: 🐛 Bug ➾ optional parameter on entrypoint not correctly generated by Taqueria makes Typescript wrong
### 🚥 Status (Internal Taqueria Team Use Only)

- [ ] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

image

My entrypoint contains an optional, when I run the taqueria type generation it creates the fields in random postiion, so my optional field here appear on first position. On Typescript, we should list all mandatory fields first 

Here the parameter in jsligo from the smart contract :

`export type removeMemberRequest = {
    member : address, 
    orgName : string,
    lastAdmin : option<address>
};`

Here the portion of the file generated by Taqueria

`type Methods = {
    removeMember: (
        lastAdmin?: address,
        member: address,
        orgName: string,
    ) => Promise<void>;
  ...  
    `

### 🆘 Steps to Reproduce?

add on optionla field on an entrypoint parameter and generate the type via taqueria plugin

### 🪵 Relevant log output

_No response_

### 🐘 How impactful is this bug?

🤔 Notable but managable

### ⏱️ Prevalance

_No response_

### 💻 Operating System

None

### 🕸️ System Architecture

None

### 🌮 Taqueria Version

v0.28.4

### 🌿 Node.js Version

_No response_

### ☎️ Contact Details

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mweichert**
# 🌮 Taqueria PR

## 🪁 Description

Fixes #1861

### CODE REVIEW

File: taqueria-plugin-contract-types/src/generator/contract-parser.ts [hunk 1]
```diff
@@ -96,7 +96,9 @@ const visitContractParameterEndpoint = (node: MMethod): TypedMethod[] => {
 	}
 
 	const nameRaw = node.annots?.[0];
-	const name = nameRaw?.startsWith('%') ? nameRaw.substr(1) : null;
+
+	// If the name is missing, then we assume its the main / default entrypoint
```
Comment (ricklove) [inline taqueria-plugin-contract-types/src/generator/contract-parser.ts:100]: Checking why this doesn't work: 

https://github.com/ecadlabs/taqueria/blob/2300f346cf72033d1f11ab12a8de658d1c04b3ba/taqueria-plugin-contract-types/src/generator/process.ts#L93

**Review by ricklove — COMMENTED** [review]
Checking default entrypoint
