### PR TITLE
🛠️ Fix ➾ During contract type generation, exclude all non-contract files such as storage files

### LINKED ISSUE #1284: 🐛 Bug ➾ Contract Types Should Ignore *.default_storage.tz and parameters.tz files
### 🆘 What happened?

contract types includes the *.default_storage.tz file

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jchenche**
# 🌮 Taqueria PR

Fixes #1284

## 🪁 Description

During contract type generation, exclude all non-contract files such as storage (default or not) files, parameter files, and expression files.

## 🪂 Pre-Merge Checklist (Definition of Done)

🚦 Required to merge:

- [ ] ⛱️ I have completed this PR template in full and updated the title appropriately
- [ ] ⛵ My code builds cleanly, and I have manually tested the changes
- [ ] 🏄‍♂️ Another team member has built this branch and done manual testing on the change
- [ ] 🏖️ New and existing unit tests pass locally and in CI
- [ ] 🔱 The test plan has been implemented and verified by an SDET
- [ ] 🦀 Automated tests have been written and added to this PR
- [ ] 🐬 I have commented my code, particularly in hard-to-understand areas
- [ ] 🤿 Corresponding changes have been made to all documentation
- [ ] 🐚 Required changes to the VScE have been made
- [ ] 🪸 Required updates to scaffolds have been made
- [ ] 🚢 The release checklist has been completed

## 🛩️ Summary of Changes

_Please include a summary of the changes to the codebase._ _Please also include relevant motivation and context for the change_
_(e.g. what was the existing behaviour, why did it break, etc.)_

## 🎢 Test Plan

_Please describe the testing strategy and plan for this PR. Keep this lightweight and anticipate any testing challenges_

## 🛸 Type of Change

- [ ] 🧽 Chore ➾
- [x] 🛠️ Fix ➾
- [ ] ✨ Feature ➾
- [ ] 👷 Refactor ➾
- [ ] 🧪 Pre-Release ➾
- [ ] 🚀 Release ➾

### CODE REVIEW

File: taqueria-plugin-contract-types/tasks.ts [hunk 1]
```diff
@@ -30,9 +30,17 @@ const generateContractTypes = (parsedArgs: Opts) =>
 		return `${contractFilename}: Types generated`;
 	};
 
+const isContractFile = (filename: string): boolean => {
+	return !filename.includes('.default_storage.')
+		&& !filename.includes('.storage.')
```
Comment (AlirezaHaghshenas) [inline taqueria-plugin-contract-types/tasks.ts:35]: It's nitpicking, but if someone names their contract like `build.storage.contract.jsligo`, this will exclude them.
But our convention for storage is that it should be right before the extension. Am I right?

**Review by AlirezaHaghshenas — APPROVED** [review]

File: taqueria-plugin-contract-types/tasks.ts (hunk 1 above)
Comment (jchenche) [reply taqueria-plugin-contract-types/tasks.ts:35]: oh it will and should exclude `build.storage.contract.jsligo`

Comment (jchenche) [reply taqueria-plugin-contract-types/tasks.ts:35]: it's CONTRACT.storage.NAME.jsligo

Comment (AlirezaHaghshenas) [reply taqueria-plugin-contract-types/tasks.ts:35]: Ah OK. Bad example. Yes. Now I remember.
